name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Deploy to EC2 with rsync
      - name: Sync files to EC2
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /home/ubuntu/bowlingapp/
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}

      # 3. Restart Streamlit on EC2
      - name: Restart Streamlit App
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            pkill -f streamlit || true
            nohup streamlit run /home/ubuntu/bowlingapp/app/app.py --server.port 8501 --server.headless true > /home/ubuntu/bowlingapp/streamlit.log 2>&1 &

