name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ubuntu
          REMOTE_PORT: 22
          SOURCE: .
          TARGET: /home/ubuntu/bowlingapp

      - name: Restart Streamlit App
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/bowlingapp
            # Optional: activate venv
            if [ -d "venv" ]; then
              source venv/bin/activate
            fi
            pip3 install --upgrade pip
            if [ -f "requirements.txt" ]; then
              pip3 install -r requirements.txt
            fi
            sudo systemctl restart streamlit

